name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --pull -t mtwebworx/blink-server-container:${{ github.sha }} \
                       -t mtwebworx/blink-server-container:latest .

      - name: Push Docker Image
        run: |
          docker push mtwebworx/blink-server-container:${{ github.sha }}
          docker push mtwebworx/blink-server-container:latest

      - name: Deploy to EC2
        run: |
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

          ssh -o ConnectTimeout=15 -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'END_SSH'
            set -e  # Fail on error
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull mtwebworx/blink-server-container:latest
            docker rm -f blink-server-container-container || true
            docker run -d \
              --name blink-server-container-container \
              -p 8080:3000 \  # Match ALB → EC2:8080 → Container:3000
              --restart unless-stopped \
              mtwebworx/blink-server-container:latest
          END_SSH
